Repository Apptive-Game-Team/GyeMong, pull requests merged in 2024-12, with the labels that each got.

#88 feat(Directing) : 연출
  Assets/Scenes/Test/JJW.meta
  Assets/Scenes/Test/JJW/TestJJW.unity
  Assets/Scenes/Test/JJW/TestJJW.unity.meta
  Assets/Scenes/Test/JJW/TutorialSceneJJW.unity
  Assets/Scenes/Test/JJW/TutorialSceneJJW.unity.meta
  Assets/Scripts/Event/SceneEvent.meta
  Assets/Scripts/Event/SceneEvent/SceneEvent.cs
  Assets/Scripts/Event/SceneEvent/SceneEvent.cs.meta
Labels: documentation

#89 Art/85
  Assets/Art Resources/GyeMong_Art.meta
  Assets/Scenes/BossTest/MidBossTest.Forest.unity
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/FiniteStateMachine.cs
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
Labels: art_resource

#90 Feat/81
  Assets/Scenes/ShaderTestScene.unity
  Assets/Scenes/ShaderTestScene.unity.meta
  Assets/Shader.meta
  Assets/Shader/FlickOutLine.shadergraph
  Assets/Shader/FlickOutLine.shadergraph.meta
  Assets/Shader/GlowLight.mat
  Assets/Shader/GlowLight.mat.meta
  Assets/Shader/GlowLight.shadergraph
  Assets/Shader/GlowLight.shadergraph.meta
  Assets/Shader/OutLine.shadergraph
  Assets/Shader/OutLine.shadergraph.meta
  Assets/Shader/Shield.mat
  Assets/Shader/Shield.mat.meta
  Assets/Shader/Shield.shadergraph
  Assets/Shader/Shield.shadergraph.meta
Labels: feature

#102 Refact/96
  Assets/Art Resources/Cainos/Pixel Art Top Down - Basic/Patch - URP 2D Lit.unitypackage.meta
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
Labels: refactoring

#115 Feature/108
  Assets/Scripts/Event/BossEvents/BossEvents.cs
  Assets/Scripts/UI/HpBarController.cs
Labels: feature

#118 Refact/103
  Assets/Scenes/BossTest/MidBossTest.Forest.unity.meta
  Assets/Scenes/BossTest/MidBossTest.unity
  Assets/Scenes/BossTest/SpringMidBoss.unity
  Assets/Scenes/BossTest/SpringMidBoss.unity.meta
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
  Assets/Scripts/Creature/MidBoss/Seed.cs
  Assets/Scripts/Creature/MidBoss/Vine.cs
  Assets/Scripts/Player/PlayerCharacter.cs
Labels: refactoring

#127 Feature/121
  Assets/Scenes/241201/SpringGuardian.unity
  Assets/Scripts/BossRoom/SpringGuadianBossRoomEntrance.cs
  Assets/Scripts/Event/Camera/CameraController.cs
Labels: feature

#130 Refact/119
  Assets/Scenes/BossTest/SpringMidBoss.unity
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/FiniteStateMachine.cs
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
Labels: refactoring

#132 Feat/131
  Assets/Scenes/241201/SpringMidBoss.unity
  Assets/Scenes/BossTest/SpringMidBoss.unity
  Assets/Scenes/BossTest/SpringMidBoss.unity.meta
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/MidBoss/Arrow.cs
  Assets/Scripts/Creature/MidBoss/MeleeAttack.cs
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
  Assets/Scripts/Creature/MidBoss/Seed.cs
  Assets/Scripts/Creature/MidBoss/Vine.cs
Labels: refactoring

#136 Feat/110
  Assets/Prefabs/Player/Player.prefab
  Assets/ScriptableObjects/Event.meta
  Assets/ScriptableObjects/Event/EventDataList.asset
  Assets/ScriptableObjects/Event/EventDataList.asset.meta
  Assets/Scripts/Data/SaveDataEvent.cs
  Assets/Scripts/Event/CinematicEvent/TextEvents.cs
  Assets/Scripts/Event/EventDataList.cs
  Assets/Scripts/Event/EventDataList.cs.meta
  Assets/Scripts/Player/PlayerCharacter.cs
Labels: feature

#138 Bug/137
  Assets/Scenes/241201/TutorialScene.unity
  Assets/Scripts/Player/PlayerCharacter.cs
Labels: bug

#140 TextEvents에 에러 수정
  Assets/Scripts/Event/CinematicEvent/TextEvents.cs
Labels: bug

#149 Refact/135
  Assets/Scenes/241201/SpringMidBoss.unity
  Assets/Scripts/BossRoom/MidBossRoomEntrance.cs
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/FiniteStateMachine.cs
  Assets/Scripts/Creature/MidBoss/Arrow.cs
  Assets/Scripts/Creature/MidBoss/MeleeAttack.cs
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
  Assets/Scripts/Creature/MidBoss/Seed.cs
  Assets/Scripts/Creature/MidBoss/Vine.cs
Labels: bug, refactoring

#152 Origin/fix/145
  Assets/Art Resources/Etc.meta
  Assets/Art Resources/Etc/BossAttack.meta
  Assets/Art Resources/Etc/BossAttack/Arrow.png
  Assets/Art Resources/Etc/BossAttack/Arrow.png.meta
  Assets/Art Resources/Etc/BossAttack/SeedArrow.png
  Assets/Art Resources/Etc/BossAttack/SeedArrow.png.meta
  Assets/Prefabs/MidBoss/MidBossArrow.prefab
  Assets/Prefabs/MidBoss/MidBossSeed.prefab
  Assets/Scenes/241201/TutorialScene.unity
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
  Assets/Scripts/Creature/MidBoss/Seed.cs
  Assets/Scripts/Event/NPC/ChatController.cs
  Assets/Scripts/Event/NPC/ChatEvents.cs
Labels: bug, documentation, art_resource

#154 Refact/151
  Assets/Scenes/241201/SpringGuardian.unity
  Assets/Scripts/BossRoom/SpringGuadianBossRoomEntrance.cs
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/Guardian/Guardian.cs
  Assets/Scripts/Creature/Guardian/RootPatternManger.cs
Labels: feature, refactoring

#157 feat(MidBossVine.prefab) : Animation 적용, 크기 변경
  Assets/Prefabs/MidBoss/MidBossVine.prefab
Labels: feature

#155 Feature/150
  Assets/Prefabs/MidBoss/MidBossArrow.prefab
  Assets/Prefabs/MidBoss/MidBossSeed.prefab
  Assets/Scenes/241201/SpringMidBoss.unity
  Assets/ScriptableObjects/Sound/SoundSourceList.asset
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/FootSoundController.cs
  Assets/Scripts/Creature/FootSoundController.cs.meta
  Assets/Scripts/Creature/MidBoss/Arrow.cs
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
  Assets/Scripts/Creature/MidBoss/Seed.cs
  Assets/Scripts/Event/Sound/SoundObject.cs
Labels: feature

#161 Bug/159
  Assets/Prefabs/Player/AttackColliderPrefab.prefab
  Assets/Scenes/241201/SpringMidBoss.unity
  Assets/Scripts/BoundarySetter.cs
  Assets/Scripts/Data/DataManager.cs
  Assets/Scripts/Event/Camera/CameraController.cs
  Assets/Scripts/Event/Sound/SoundManager.cs
  Assets/Scripts/InputSystem/InputManager.cs
  Assets/Scripts/Player/PlayerSoundController.cs
Labels: bug

#160 bug/158
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/Player/Player.prefab
  Assets/Prefabs/Rune/RuneCanvas.prefab
  Assets/Prefabs/UI/OptionController.prefab
  Assets/ScriptableObjects/Sound/SoundSourceList.asset
  Assets/Scripts/Player/PlayerCharacter.cs
  Assets/Scripts/Player/PlayerSoundController.cs
Labels: bug, art_resource

#164 refact(Creature.cs)
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
Labels: bug

#170 fix(CameraController.cs, EffectManager.cs) : 카메라 흔들림 조정
  Assets/Scripts/Event/Camera/CameraController.cs
  Assets/Scripts/Event/Effect/EffectManager.cs
Labels: refactoring

#172 Feat/167
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/Player/AttackColliderPrefab.prefab
  Assets/Scenes/241201/SpringGuardian.unity
  Assets/Scenes/241201/SpringMidBoss.unity
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
  Assets/Scripts/Event/BossEvents/BossEvents.cs
  Assets/Scripts/Event/Effect/EffectManager.cs
  Assets/Scripts/Player/PlayerCharacter.cs
  Assets/Scripts/UI/HpBarController.cs
Labels: feature
