Repository Apptive-Game-Team/GyeMong, pull requests merged in 2024-11, with the labels that each got.

#10 Get InputManager from Lucy
  Assets/Prefabs/InputManager.prefab
  Assets/Prefabs/InputManager.prefab.meta
  Assets/Scenes/CameraTestScene.unity
  Assets/Scripts/InputSystem.meta
  Assets/Scripts/InputSystem/IInputListener.cs
  Assets/Scripts/InputSystem/IInputListener.cs.meta
  Assets/Scripts/InputSystem/InputManager.cs
  Assets/Scripts/InputSystem/InputManager.cs.meta
Labels: feature

#31 Feat/21
  Assets/Art Resources/Simple 2D Platformer BE2.meta
  Assets/Art Resources/Simple 2D Platformer BE2/App Icon.png
  Assets/Art Resources/Simple 2D Platformer BE2/App Icon.png.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Demo.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Demo/Demo.unity
  Assets/Art Resources/Simple 2D Platformer BE2/Demo/Demo.unity.meta
  Assets/Art Resources/Simple 2D Platformer BE2/ReadMe.meta
  Assets/Art Resources/Simple 2D Platformer BE2/ReadMe/Icon.png
  Assets/Art Resources/Simple 2D Platformer BE2/ReadMe/Icon.png.meta
  Assets/Art Resources/Simple 2D Platformer BE2/ReadMe/Scripts.meta
  Assets/Art Resources/Simple 2D Platformer BE2/ReadMe/Scripts/Editor.meta
  Assets/Art Resources/Simple 2D Platformer BE2/ReadMe/Scripts/Editor/ReadmeEditorBE2.cs
  Assets/Art Resources/Simple 2D Platformer BE2/ReadMe/Scripts/Editor/ReadmeEditorBE2.cs.meta
  Assets/Art Resources/Simple 2D Platformer BE2/ReadMe/Scripts/ReadmeBE2.cs
  Assets/Art Resources/Simple 2D Platformer BE2/ReadMe/Scripts/ReadmeBE2.cs.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Readme.asset
  Assets/Art Resources/Simple 2D Platformer BE2/Readme.asset.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Bottom.asset
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Bottom.asset.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Coins.png
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Coins.png.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Enemy.png
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Enemy.png.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Finish.asset
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Finish.asset.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/New Palette.prefab
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/New Palette.prefab.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Objects.png
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Objects.png.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Platforms.png
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Platforms.png.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Player.png
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Player.png.meta
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Spike.asset
  Assets/Art Resources/Simple 2D Platformer BE2/Sprites/Spike.asset.meta
  Assets/Prefabs/MidBoss.meta
  Assets/Prefabs/MidBoss/MidBossArrow.prefab
  Assets/Prefabs/MidBoss/MidBossArrow.prefab.meta
  Assets/Prefabs/MidBoss/MidBossSeed.prefab
  Assets/Prefabs/MidBoss/MidBossSeed.prefab.meta
  Assets/Prefabs/MidBoss/MidBossVine.prefab
  Assets/Prefabs/MidBoss/MidBossVine.prefab.meta
  Assets/Scenes/MidBossTest.unity
  Assets/Scenes/MidBossTest.unity.meta
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/MidBoss.cs
  Assets/Scripts/Creature/MidBoss.meta
  Assets/Scripts/Creature/MidBoss/Arrow.cs
  Assets/Scripts/Creature/MidBoss/Arrow.cs.meta
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
  Assets/Scripts/Creature/MidBoss/MidBoss.cs.meta
  Assets/Scripts/Creature/MidBoss/Seed.cs
  Assets/Scripts/Creature/MidBoss/Seed.cs.meta
  Assets/Scripts/Creature/MidBoss/Vine.cs
  Assets/Scripts/Creature/MidBoss/Vine.cs.meta
  Assets/Scripts/Creature/Player.cs
  Assets/Scripts/Creature/PlayerDemo.cs
  Assets/Scripts/Creature/PlayerDemo.cs.meta
Labels: feature

#45 fix(GenerateTree.cs) : 생성된 나무를 TreeGenerator의 자손으로 설정
  Assets/JJW/Scene/CharacterTest1110.unity.meta
  Assets/KHJ/Scripts/Puzzle1/GenerateTree.cs
  Assets/Scenes/MidBossTest.unity.meta
Labels: refactoring

#49 Feature/48
  Assets/Art Resources/Cainos/Pixel Art Top Down - Basic/Patch - URP 2D Lit.unitypackage.meta
  Assets/JJW/Scene/CharacterTest1110.unity.meta
  Assets/Scenes/EventTestScene/SpringMainNPCVersion.unity.meta
  Assets/Scripts/Event/EventObject.cs
  Assets/Scripts/Event/Events.cs
  Assets/Scripts/Event/NPC/ChatController.cs
  Assets/Scripts/Event/NPC/ChatEvents.cs
Labels: feature

#50 Origin/fix/42
  Assets/JJW/Animator/Player.controller
  Assets/JJW/Scene/CharacterTest1110.unity
  Assets/JJW/Scene/CharacterTest1110.unity.meta
  Assets/JJW/Scripts/PlayerCharacter.cs
Labels: documentation

#52 feat(CharacterBattle)
  Assets/JJW/Prefabs/AttackColliderPrefab.prefab
  Assets/JJW/Prefabs/AttackColliderPrefab.prefab.meta
  Assets/JJW/Scene/Text1117.unity
  Assets/JJW/Scene/Text1117.unity.meta
  Assets/JJW/Scripts/AttackCollider.cs
  Assets/JJW/Scripts/AttackCollider.cs.meta
  Assets/JJW/Scripts/PlayerCharacter.cs
  Assets/Scripts/Creature/Creature.cs
Labels: feature

#66 feat/65
  Assets/Art Resources/Cainos/Pixel Art Top Down - Basic/Patch - URP 2D Lit.unitypackage.meta
  Assets/Art Resources/Cainos/Pixel Art Top Down - Basic/Tile Palette/Props/Props.prefab
  Assets/Scenes/SpringGuardianMapTest.unity
  Assets/Scenes/SpringGuardianMapTest.unity.meta
  Assets/Scenes/Tilemap_Setting/SpringGuardianMap_Forest.unity
  Assets/Scenes/Tilemap_Setting/SpringGuardianMap_Forest.unity.meta
  Assets/Scenes/Tilemap_Setting/SpringGuardianMap_Temple.unity
  Assets/Scenes/Tilemap_Setting/SpringGuardianMap_Temple.unity.meta
Labels: feature

#74 Feat/60
  Assets/Prefabs/Guardian/Cube.prefab
  Assets/Prefabs/Guardian/Floor.prefab
  Assets/Prefabs/MeleeAttack.prefab
  Assets/Prefabs/MeleeAttack.prefab.meta
  Assets/Scenes/BossTest.meta
  Assets/Scenes/BossTest/MidBossTest.unity
  Assets/Scenes/BossTest/MidBossTest.unity.meta
  Assets/Scenes/BossTest/SpringGuardianTest.unity
  Assets/Scenes/BossTest/SpringGuardianTest.unity.meta
  Assets/Scripts/BossRoom/MidBossRoomEntrance.cs
  Assets/Scripts/BossRoom/SpringGuadianBossRoomEntrance.cs
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/FiniteStateMachine.cs
  Assets/Scripts/Creature/FiniteStateMachine.cs.meta
  Assets/Scripts/Creature/Guardian/Cube.cs
  Assets/Scripts/Creature/Guardian/Guardian.cs
  Assets/Scripts/Creature/Guardian/RootPatternManger.cs
  Assets/Scripts/Creature/Guardian/RootPatternManger.cs.meta
  Assets/Scripts/Creature/MidBoss/Arrow.cs
  Assets/Scripts/Creature/MidBoss/MeleeAttack.cs
  Assets/Scripts/Creature/MidBoss/MeleeAttack.cs.meta
  Assets/Scripts/Creature/MidBoss/MidBoss.cs
  ProjectSettings/TagManager.asset
Labels: feature, refactoring

#84 Feat Boss Test Scene
  Assets/Prefabs/Guardian/Cube.prefab
  Assets/Scenes/241123/SpringGuardian.unity
  Assets/Scenes/BossTest/MidBossTest.Forest.unity
  Assets/Scenes/BossTest/MidBossTest.Forest.unity.meta
  Assets/Scenes/BossTest/MidBossTest.unity
  Assets/Scenes/BossTest/SpringGuardianTest.Temple.unity
  Assets/Scenes/BossTest/SpringGuardianTest.Temple.unity.meta
  Assets/Scenes/BossTest/SpringGuardianTest.unity
  Assets/Scripts/Creature/Guardian/Cube.cs
  Assets/Scripts/Creature/Guardian/Floor.cs
  Assets/Scripts/Creature/Guardian/Root.cs
  Assets/Scripts/Creature/Guardian/RootPatternManger.cs
  Assets/Scripts/Creature/MidBoss/Arrow.cs
  Assets/Scripts/Creature/MidBoss/MeleeAttack.cs
  Assets/Scripts/Creature/MidBoss/Seed.cs
  Assets/Scripts/Creature/MidBoss/Vine.cs
Labels: feature
