Repository Apptive-Game-Team/GyeMong, pull requests merged in 2025-02, with the labels that each got.

#194 Refact/186
  Assets/Scenes/Com2us_Version/SpringMidBoss.unity
  Assets/Scripts/Creature/AnimationManage.meta
  Assets/Scripts/Creature/AnimationManage/AnimationDataList.asset
  Assets/Scripts/Creature/AnimationManage/AnimationDataList.asset.meta
  Assets/Scripts/Creature/AnimationManage/AnimationDataList.cs
  Assets/Scripts/Creature/AnimationManage/AnimationDataList.cs.meta
  Assets/Scripts/Creature/AnimationManage/AnimationManager.cs
  Assets/Scripts/Creature/AnimationManage/AnimationManager.cs.meta
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/MidBoss/Elf.cs
Labels: feature, refactoring

#202 Feat/193
  Assets/Prefabs/Player/Player.prefab
  Assets/Scenes/BattleTest/ControlTest.unity
  Assets/Scenes/BattleTest/ControlTest.unity.meta
  Assets/Scripts/InputSystem/InputManager.cs
  Assets/Scripts/Player/PlayerCharacter.cs
  Assets/Shader/OutLineEffect.mat
  Assets/Shader/SkillParticleEffect.shadergraph
  ProjectSettings/ProjectSettings.asset
Labels: feature, refactoring

#204 Bug/201
  Assets/Prefabs/Player/AttackColliderPrefab.prefab
  Assets/Scenes/Com2us_Version/SpringMidBoss.unity
  Assets/Scripts/Creature/MidBoss/Arrow.cs
  Assets/Scripts/Creature/MidBoss/Elf.cs
  Assets/Scripts/Creature/MidBoss/Seed.cs
  Assets/Scripts/Event/BossEvents/BossEvents.cs
  Assets/Shader/OutLineEffect.mat
Labels: bug

#209 Fix/206
  Assets/Prefabs/Boss/Guardian/Cube.prefab
  Assets/Prefabs/Boss/Guardian/Floor.prefab
  Assets/Prefabs/Boss/Guardian/Guardian.prefab
  Assets/Prefabs/Boss/Guardian/Root.prefab
  Assets/Prefabs/Boss/Guardian/Shockwave.prefab
  Assets/Scenes/Com2us_Version/SpringGuardian.unity
  Assets/Scenes/Com2us_Version/SpringMidBoss.unity
  Assets/Scripts/Creature/Boss.cs
  Assets/Scripts/Creature/Guardian/Cube.cs
  Assets/Scripts/Creature/Guardian/Floor.cs
  Assets/Scripts/Creature/Guardian/Golem.cs
  Assets/Scripts/Creature/Guardian/Root.cs
  Assets/Scripts/Creature/Guardian/RootPatternManger.cs
  Assets/Scripts/Creature/MidBoss/Elf.cs
  Assets/Scripts/Creature/MidBoss/MeleeAttack.cs
  Assets/Shader/OutLineEffect.mat
  ProjectSettings/Physics2DSettings.asset
Labels: bug

#211 Implment Elf Down Ani
  Assets/Scenes/Com2us_Version/SpringMidBoss.unity
  Assets/Scripts/Creature/MidBoss/Elf.cs
  Assets/Shader/OutLineEffect.mat
Labels: art_resource

#216 Fix/214
  Assets/Prefabs/GameManager.prefab
  Assets/Prefabs/NPC Variant.prefab
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad1.unity
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad1.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad2.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad3.unity
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad3.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringBelowRoad1.unity
  Assets/Scenes/DemoDay_Version_0207/SpringBelowRoad1.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringBelowRoad2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringBelowRoad2.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringElf.unity
  Assets/Scenes/DemoDay_Version_0207/SpringElf.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringGolem.unity
  Assets/Scenes/DemoDay_Version_0207/SpringGolem.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringLeftRoad1.unity
  Assets/Scenes/DemoDay_Version_0207/SpringLeftRoad1.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringLeftRoad2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringLeftRoad2.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringMain.unity
  Assets/Scenes/DemoDay_Version_0207/SpringMain.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringMaze.unity
  Assets/Scenes/DemoDay_Version_0207/SpringMaze.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringPuzzle2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringRightRoad1.unity
  Assets/Scenes/DemoDay_Version_0207/SpringRightRoad1.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringRightRoad2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringRightRoad2.unity.meta
  Assets/Scenes/DemoDay_Version_0207/SpringTutorialScene.unity
  Assets/Scenes/DemoDay_Version_0207/SpringTutorialScene.unity.meta
  Assets/ScriptableObjects/Portal/SceneDataList.asset
  Assets/Scripts/Puzzle2/Puzzle2.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: bug

#219 Fix/218
  Assets/Prefabs/Event/Portal Variant.prefab
  Assets/Prefabs/Event/Portal Variant.prefab.meta
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad1.unity
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad3.unity
  Assets/Scenes/DemoDay_Version_0207/SpringBelowRoad1.unity
  Assets/Scenes/DemoDay_Version_0207/SpringBelowRoad2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringElf.unity
  Assets/Scenes/DemoDay_Version_0207/SpringGolem.unity
  Assets/Scenes/DemoDay_Version_0207/SpringLeftRoad1.unity
  Assets/Scenes/DemoDay_Version_0207/SpringLeftRoad2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringMain.unity
  Assets/Scenes/DemoDay_Version_0207/SpringMaze.unity
  Assets/Scenes/DemoDay_Version_0207/SpringPuzzle2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringRightRoad1.unity
  Assets/Scenes/DemoDay_Version_0207/SpringRightRoad2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringTutorialScene.unity
Labels: bug

#221 Fix/220
  Assets/Prefabs/Boss/MidBoss/MidBossArrow.prefab
  Assets/Prefabs/Boss/MidBoss/MidBossSeed.prefab
  Assets/Scenes/DemoDay_Version_0207/SpringTutorialScene.unity
  Assets/Scripts/Creature/MidBoss/Seed.cs
  Assets/Shader/OutLineEffect.mat
Labels: bug

#226 Fix/217
  Assets/Art Resources/Cainos2/Pixel Art Top Down - Basic/Texture/TX Props.png.meta
  Assets/Prefabs/UI/OptionController.prefab
  Assets/Scripts/Data/DataManager.cs
  Assets/Scripts/InputSystem/InputManager.cs
  Assets/Scripts/Option/KeyMapping/Keys/RunKey.cs
  Assets/Scripts/Option/KeyMapping/Keys/RunKey.cs.meta
  Assets/Scripts/Option/OptionButtons/OptionExitButton.cs
  Assets/Scripts/Player/PlayerCharacter.cs
  Assets/Scripts/Puzzle1/MazeDarkness.cs
  Assets/Scripts/TItle/ContinueButton.cs
  Assets/Scripts/TItle/StartButton.cs
  Assets/Scripts/UI/SkillGaugeController.cs
  ProjectSettings/TagManager.asset
Labels: bug

#229 Fix/223
  Assets/Prefabs/Player/Player.prefab
  Assets/Prefabs/Rune/Rework/RuneIcon.prefab
  Assets/Prefabs/Rune/RuneCanvas.prefab
  Assets/Scripts/Event/Camera/CameraController.cs
  Assets/Scripts/Event/CinematicEvent/CinematicEvents.cs
  Assets/Scripts/Player/GrazeController.cs
Labels: bug, feature

#230 Feature/225
  Assets/Prefabs/GameManager.prefab
  Assets/Scenes/DemoDay_Version_0207/SpringMain.unity
  Assets/Scripts/Player/PlayerCharacter.cs
  Assets/Scripts/UI/GaugeController.cs
  Assets/Scripts/UI/GaugeController.cs.meta
  Assets/Scripts/UI/PlayerHpController.cs
  Assets/Scripts/UI/PlayerHpController.cs.meta
  Assets/Scripts/UI/SkillGaugeController.cs
Labels: feature

#231 Origin/feat/222
  Assets/Prefabs/MapBoundarySetter.prefab
  Assets/Scenes/DemoDay_Version_0207/SpringAboveRoad2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringGolem.unity
  Assets/Scenes/DemoDay_Version_0207/SpringMain.unity
  Assets/Scenes/DemoDay_Version_0207/SpringPuzzle2.unity
  Assets/Scenes/DemoDay_Version_0207/SpringRightRoad1.unity
  Assets/Scenes/DemoDay_Version_0207/SpringRightRoad2.unity
  Assets/Scripts/BoundarySetter.cs
Labels: bug

#236 Fix/235
  Assets/Prefabs/UI/OptionController.prefab
  Assets/Scenes/DemoDay_Version_0207/SpringMaze.unity
  Assets/Scripts/Creature/Boss/EnemyAttackInfo.cs
  Assets/Scripts/Creature/Boss/EnemyAttackInfo.cs.meta
  Assets/Scripts/Creature/Boss/Spring/Elf/Arrow.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Elf.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/MeleeAttack.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Seed.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Vine.cs
  Assets/Scripts/Creature/Boss/Spring/Golem/Cube.cs
  Assets/Scripts/Creature/Boss/Spring/Golem/Floor.cs
  Assets/Scripts/Creature/Boss/Spring/Golem/Golem.cs
  Assets/Scripts/Creature/Boss/Spring/Golem/GuardianAttack.cs
  Assets/Scripts/Creature/Boss/Spring/Golem/Root.cs
  Assets/Scripts/Creature/Player/Component/Collider/HtiCollider.cs
  Assets/Scripts/Creature/Player/Controller/GrazeController.cs
  Assets/Scripts/Creature/Player/PlayerCharacter.cs
  Assets/Scripts/Map/Puzzle/Maze/GenerateMaze.cs
  Assets/Scripts/System/Event/Event/Input/ControlEvents.cs
  Assets/Scripts/System/UI/Option/Controller/KeyMapping.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys.meta
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/AttackKey.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/AttackKey.cs.meta
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/DashKey.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/DashKey.cs.meta
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/InteractionKey.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/InteractionKey.cs.meta
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/MoveDownKey.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/MoveDownKey.cs.meta
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/MoveLeftKey.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/MoveRightKey.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/MoveRightKey.cs.meta
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/MoveUpKey.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/MoveUpKey.cs.meta
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/RunePageKey.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/RunePageKey.cs.meta
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/SkillKey.cs
  Assets/Scripts/System/UI/Option/KeyMapping/Keys/SkillKey.cs.meta
Labels: fix, refactoring, boss(part)

#239 fix(SpringBelowRoad2.unity) : 알 수 없는 collider 제거
  Assets/Scenes/DemoDay_Version_0207/SpringBelowRoad2.unity
Labels: fix

#242 Fix/237
  Assets/Prefabs/Boss/Guardian/Floor.prefab
  Assets/Scenes/DemoDay_Version_0207/SpringElf.unity
  Assets/Scenes/DemoDay_Version_0207/SpringGolem.unity
  Assets/Scenes/DemoDay_Version_0207/SpringMain.unity
  Assets/Scripts/Creature/Boss/Boss.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Elf.cs
  Assets/Scripts/Creature/Boss/Spring/Golem/Golem.cs
  Assets/Scripts/Creature/Player/PlayerCharacter.cs
Labels: fix, art_resource, boss(part)

#248 Fix/243
  Assets/Prefabs/Boss/BossUi.meta
  Assets/Prefabs/Boss/BossUi/HpBarCanvas.prefab
  Assets/Prefabs/Boss/BossUi/HpBarCanvas.prefab.meta
  Assets/Prefabs/Boss/MidBoss/MidBossArrow.prefab
  Assets/Prefabs/Boss/MidBoss/MidBossSeed.prefab
  Assets/Prefabs/GameManager.prefab
  Assets/Scenes/DemoDay_Version_0207/SpringElf.unity
  Assets/Scenes/DemoDay_Version_0207/SpringGolem.unity
  Assets/Scripts/Creature/Boss/Boss.cs
  Assets/Scripts/System/Event/Controller/EffectManager.cs
  Assets/Shader/OutLineEffect.mat
Labels: fix, refactoring, boss(part)
