Repository Apptive-Game-Team/GyeMong, pull requests merged in 2025-07, with the labels that each got.

#369 Feat/367
  Assets/Resources/Prefabs/TileMap/beach/BeachMap.prefab
  Assets/Scenes/Alpha Version/a0.0.1-1/SpringGarden.unity
  Assets/Scenes/YJ_map/beach.unity
  Assets/Scripts/GyeMong/EventSystem/Event/PopupWindowEvents.cs
  Assets/Scripts/GyeMong/GameSystem/Creature/Mob/StateMachineMob/Minion/Slime/DivisionSlime.cs
  Assets/Scripts/GyeMong/GameSystem/Creature/Mob/StateMachineMob/Minion/Slime/SlimeBase.cs
  Assets/Scripts/GyeMong/GameSystem/Creature/Mob/StateMachineMob/StateMachineMob.cs
  Assets/Scripts/GyeMong/GameSystem/Creature/Player/PlayerCharacter.cs
  Assets/Scripts/GyeMong/GameSystem/Map/MapEvent/SpringGardenEvent.cs
Labels: content(part)

#374 fix(PlayerCharacter.cs) : 플레이어 공격 시 움직임 버그 수정
  Assets/Scripts/GyeMong/GameSystem/Creature/Player/PlayerCharacter.cs
Labels: fix

#380 feat(Scene, Portal Id) : 포탈과 관련된 Id 정상화
  Assets/Resources/ScriptableObjects/Portal/AlphaPortalDataList.asset
  Assets/Resources/ScriptableObjects/Portal/AlphaSceneDataList.asset
  Assets/Scenes/Alpha Version/a0.0.1-1/SpringBeach.unity
  Assets/Scenes/Alpha Version/a0.0.1-1/SpringBeach.unity.meta
  Assets/Scenes/StageSelect/StageSelectPage.unity
  Assets/Scripts/GyeMong/GameSystem/Map/Portal/PortalDataList.cs
  Assets/Scripts/GyeMong/GameSystem/Map/Portal/SceneDataList.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: fix

#398 Feat/397
  Assets/Scenes/Alpha Version/a0.0.1-1/SpringShadowIsland.unity
  Assets/Scripts/GyeMong/GameSystem/Creature/Mob/StateMachineMob/Boss/Spring/Elf/Elf.cs
  Assets/Scripts/GyeMong/GameSystem/Creature/Mob/StateMachineMob/Boss/Summer/NagaRogue/NagaRogue.cs
  Assets/Scripts/GyeMong/GameSystem/Creature/Mob/StateMachineMob/Minion/ShadowOfHero/ShadowOfHero.cs
Labels: boss(part), effect(part)
