Repository Apptive-Game-Team/GyeMong, pull requests merged in 2025-03, with the labels that each got.

#255 Feat/252
  Assets/Scenes/EventTest.meta
  Assets/Scenes/EventTest/SpringElfTest.unity
  Assets/Scenes/EventTest/SpringElfTest.unity.meta
  Assets/Scenes/EventTest/SpringMainTest.unity
  Assets/Scenes/EventTest/SpringMainTest.unity.meta
  Assets/Scripts/Creature/Event.meta
  Assets/Scripts/Creature/Event/EventCreature.cs
  Assets/Scripts/Creature/Event/EventCreature.cs.meta
  Assets/Scripts/System/Event/Event/CinematicEvent/AnimationControllEvents.cs
Labels: feature, content(part)

#261 Feature/259
  Assets/Prefabs/Player/Player.prefab
  Assets/Scenes/RuneTest.meta
  Assets/ScriptableObjects/Player.meta
  Assets/ScriptableObjects/Player/PlayerStatData.asset
  Assets/ScriptableObjects/Player/PlayerStatData.asset.meta
  Assets/Scripts/Creature/Player/Component/Collider/AttackCollider.cs
  Assets/Scripts/Creature/Player/Component/StatComponent.cs
  Assets/Scripts/Creature/Player/Component/StatComponent.cs.meta
  Assets/Scripts/Creature/Player/Component/StatData.cs
  Assets/Scripts/Creature/Player/Component/StatData.cs.meta
  Assets/Scripts/Creature/Player/Controller/GrazeController.cs
  Assets/Scripts/Creature/Player/PlayerCharacter.cs
  Assets/Scripts/System/UI/Game/PlayerUI/PlayerHpController.cs
  Assets/Scripts/System/UI/Game/PlayerUI/SkillGaugeController.cs
  Assets/Scripts/Visual/Object/FlowerObj.cs
Labels: level_design(part)

#271 Feature/269
  Assets/Prefabs/Map/Spring/ShadowForest/ShadowOfHero.prefab
  Assets/Prefabs/Minion/Slime/FireflySlime.prefab
  Assets/Prefabs/Minion/Slime/FireflySlime.prefab.meta
  Assets/Scenes/SpringRemaster/SpringShadowForestScene.unity
  Assets/Scripts/Creature/Minion/Slime/Components.meta
  Assets/Scripts/Creature/Minion/Slime/Components/SlimeAnimator.cs
  Assets/Scripts/Creature/Minion/Slime/Components/SlimeAnimator.cs.meta
  Assets/Scripts/Creature/Minion/Slime/Components/SlimeSprites.cs
  Assets/Scripts/Creature/Minion/Slime/Components/SlimeSprites.cs.meta
  Assets/Scripts/Creature/Minion/Slime/FireflySlime.cs
  Assets/Scripts/Creature/Minion/Slime/FireflySlime.cs.meta
  Assets/Scripts/Creature/Minion/Slime/Slime.cs
  Assets/Scripts/Creature/Minion/Slime/SlimeBase.cs
  Assets/Scripts/Creature/Minion/Slime/SlimeBase.cs.meta
  Assets/Scripts/Creature/Minion/Spawner.meta
  Assets/Scripts/Creature/Minion/Spawner/FireflySlimeSpawner.cs
  Assets/Scripts/Creature/Minion/Spawner/FireflySlimeSpawner.cs.meta
  Assets/Scripts/Creature/Minion/Spawner/SlimeSpawner.cs
  Assets/Scripts/Creature/Minion/Spawner/SlimeSpawner.cs.meta
  Assets/Scripts/Map/Puzzle/FogMaze/FogController.cs
Labels: feature, content(part), adventure(part)

#267 Feat/262
  Assets/Plugins.meta
  Assets/Plugins/Demigiant.meta
  Assets/Plugins/Demigiant/DOTween.meta
  Assets/Plugins/Demigiant/DOTween/DOTween.XML
  Assets/Plugins/Demigiant/DOTween/DOTween.XML.meta
  Assets/Plugins/Demigiant/DOTween/DOTween.dll
  Assets/Plugins/Demigiant/DOTween/DOTween.dll.meta
  Assets/Plugins/Demigiant/DOTween/Editor.meta
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML.meta
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.dll
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.dll.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg.meta
  Assets/Plugins/Demigiant/DOTween/Modules.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs.meta
  Assets/Plugins/Demigiant/DOTween/readme.txt
  Assets/Plugins/Demigiant/DOTween/readme.txt.meta
  Assets/Prefabs/Minion/Slime/DivisionSlime.prefab
  Assets/Prefabs/Minion/Slime/DivisionSlime.prefab.meta
  Assets/Prefabs/Minion/Slime/MiniSlime.prefab
  Assets/Prefabs/Minion/Slime/MiniSlime.prefab.meta
  Assets/Resources/DOTweenSettings.asset
  Assets/Resources/DOTweenSettings.asset.meta
  Assets/Scenes/EventTest/DivisionSlimeTest.unity
  Assets/Scenes/EventTest/DivisionSlimeTest.unity.meta
  Assets/Scripts/Creature/Minion/Slime/DivisionSlime.cs
  Assets/Scripts/Creature/Minion/Slime/DivisionSlime.cs.meta
  Assets/Scripts/Creature/Minion/Slime/RangedAttack.cs
  Assets/Scripts/Creature/Minion/Slime/RangedAttack.cs.meta
  Assets/Scripts/Creature/Minion/Slime/SlimeAnimator.cs
  Assets/Scripts/System/Event/Event/EventScene.meta
  Assets/Scripts/System/Event/Event/EventScene/EventScenes.cs
  Assets/Scripts/System/Event/Event/EventScene/EventScenes.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: feature, content(part)

#268 Feature/263
  Assets/Prefabs/GlobalLight2D.prefab
  Assets/Prefabs/Map/Spring/ShadowForest.meta
  Assets/Prefabs/Map/Spring/ShadowForest/ShadowForestEvents.prefab
  Assets/Prefabs/Map/Spring/ShadowForest/ShadowForestEvents.prefab.meta
  Assets/Prefabs/Map/Spring/ShadowForest/ShadowOfHero.prefab
  Assets/Prefabs/Map/Spring/ShadowForest/ShadowOfHero.prefab.meta
  Assets/Prefabs/Map/Spring/Town.meta
  Assets/Prefabs/Map/Spring/Town/Eldin Variant.prefab
  Assets/Prefabs/Map/Spring/Town/Eldin Variant.prefab.meta
  Assets/Prefabs/Minion/Slime/FireflySlime.prefab
  Assets/Prefabs/Minion/Slime/FireflySlime.prefab.meta
  Assets/Resources/Quests/Spring/ShadowForest.meta
  Assets/Resources/Quests/Spring/ShadowForest/ShadowForestQuest.asset
  Assets/Resources/Quests/Spring/ShadowForest/ShadowForestQuest.asset.meta
  Assets/Scenes/SpringRemaster/SpringBeachScene.unity
  Assets/Scenes/SpringRemaster/SpringShadowForestScene.unity
  Assets/Scenes/SpringRemaster/SpringShadowForestScene.unity.meta
  Assets/Scenes/SpringRemaster/SpringTown.unity
  Assets/Scenes/SpringRemaster/TemplateScene.scenetemplate
  Assets/Scenes/SpringRemaster/TemplateScene.unity
  Assets/ScriptableObjects/Portal/RemasterPortalDataList.asset
  Assets/ScriptableObjects/Portal/RemasterSceneDataList.asset
  Assets/Scripts/Creature/Minion/ShadowOfHero.meta
  Assets/Scripts/Creature/Minion/ShadowOfHero/ShadowMovementController.cs
  Assets/Scripts/Creature/Minion/ShadowOfHero/ShadowMovementController.cs.meta
  Assets/Scripts/Creature/Minion/ShadowOfHero/ShadowOfHero.cs
  Assets/Scripts/Creature/Minion/ShadowOfHero/ShadowOfHero.cs.meta
  Assets/Scripts/Creature/Minion/Slime/Components.meta
  Assets/Scripts/Creature/Minion/Slime/Components/SlimeAnimator.cs
  Assets/Scripts/Creature/Minion/Slime/Components/SlimeAnimator.cs.meta
  Assets/Scripts/Creature/Minion/Slime/Components/SlimeSprites.cs
  Assets/Scripts/Creature/Minion/Slime/Components/SlimeSprites.cs.meta
  Assets/Scripts/Creature/Minion/Slime/FireflySlime.cs
  Assets/Scripts/Creature/Minion/Slime/FireflySlime.cs.meta
  Assets/Scripts/Creature/Minion/Slime/Slime.cs
  Assets/Scripts/Creature/Minion/Slime/SlimeBase.cs
  Assets/Scripts/Creature/Minion/Slime/SlimeBase.cs.meta
  Assets/Scripts/Creature/Minion/Spawner.meta
  Assets/Scripts/Creature/Minion/Spawner/FireflySlimeSpawner.cs
  Assets/Scripts/Creature/Minion/Spawner/FireflySlimeSpawner.cs.meta
  Assets/Scripts/Creature/Minion/Spawner/SlimeSpawner.cs
  Assets/Scripts/Creature/Minion/Spawner/SlimeSpawner.cs.meta
  Assets/Scripts/Map/Puzzle/FogMaze/FogController.cs
  Assets/Scripts/Map/Puzzle/Maze/DarknessController.cs
  Assets/Scripts/Map/Puzzle/Maze/MazeDarkness.cs
  Assets/Scripts/System/Event/Event/CinematicEvent/CinematicEvents.cs
  Assets/Scripts/System/Game/DynamicGameObjectCreator.cs
  Assets/Scripts/System/Game/DynamicGameObjectCreator.cs.meta
  Assets/Scripts/System/Game/Portal/PortalDataList.cs
  Assets/Scripts/System/Game/Portal/PortalManager.cs
  Assets/Scripts/System/Game/Portal/SceneDataList.cs
  Assets/Scripts/System/Game/Quest/Component/QuestComponent.cs
Labels: feature, content(part), adventure(part)

#279 Fix(Elf.cs) : 클래스명 오타 수정
  Assets/Scripts/Creature/Boss/Spring/Elf/Elf.cs
Labels: boss(part)

#276 Fix/274
  Assets/Scenes/SpringRemaster/SpringBeachScene.unity
  Assets/Scripts/Creature/Minion/MobSpawner.cs
  Assets/Scripts/Creature/Minion/Slime/FireflySlime.cs
  Assets/Scripts/Creature/Minion/Slime/Slime.cs
  Assets/Scripts/Creature/Minion/Slime/SlimeBase.cs
  Assets/Scripts/Creature/Minion/Spawner/SlimeSpawner.cs
  Assets/Scripts/System/Game/DynamicGameObjectCreator.cs
  Assets/Scripts/Util/ObjectCreator/ObjectPool.cs
Labels: fix, content(part)

#272 Feat/270
  Assets/Prefabs/InGameManager.prefab
  Assets/Prefabs/SpeechBubble.prefab
  Assets/Prefabs/SpeechBubble.prefab.meta
  Assets/Scenes/EventTest/SpringMainTest.unity
  Assets/Scripts/Creature/Player/PlayerCharacter.cs
  Assets/Scripts/System/Event/Controller/ChatController.cs
  Assets/Scripts/System/Event/Event/Chat/ChatEvents.cs
  Assets/Scripts/System/Event/Event/Input/ControlEvents.cs
Labels: feature, content(part)

#282 Feature/275
  Assets/Prefabs/InGameManager.prefab
  Assets/Prefabs/Map/Test.meta
  Assets/Prefabs/Map/Test/Brick.prefab
  Assets/Prefabs/Map/Test/Brick.prefab.meta
  Assets/Scenes/SpringRemaster/SpringShadowForestScene.unity
  Assets/Scripts/System/Event/Event/Data/SaveDataEvent.cs
  Assets/Scripts/System/Game/Object/Persisted.meta
  Assets/Scripts/System/Game/Object/Persisted/IPersistedComponent.cs
  Assets/Scripts/System/Game/Object/Persisted/IPersistedComponent.cs.meta
  Assets/Scripts/System/Game/Object/Persisted/PersistedGameObject.cs
  Assets/Scripts/System/Game/Object/Persisted/PersistedGameObject.cs.meta
  Assets/Scripts/System/Game/Object/Persisted/PersistedGameObjectManager.cs
  Assets/Scripts/System/Game/Object/Persisted/PersistedGameObjectManager.cs.meta
  Assets/Scripts/System/Game/Portal/PortalManager.cs
Labels: feature

#288 Feature/283
  Assets/Prefabs/Minion/ShadowOfHero.meta
  Assets/Prefabs/Minion/ShadowOfHero/ShadowOfHero Variant.prefab
  Assets/Prefabs/Minion/ShadowOfHero/ShadowOfHero Variant.prefab.meta
  Assets/Prefabs/Minion/ShadowOfHero/ShadowRangeAttack.prefab
  Assets/Prefabs/Minion/ShadowOfHero/ShadowRangeAttack.prefab.meta
  Assets/Prefabs/Minion/ShadowOfHero/SwordAura.prefab
  Assets/Prefabs/Minion/ShadowOfHero/SwordAura.prefab.meta
  Assets/Prefabs/Player/Player.prefab
  Assets/Resources/Prefabs.meta
  Assets/Resources/Prefabs/Airborne.meta
  Assets/Resources/Prefabs/Airborne/Shadow.prefab
  Assets/Resources/Prefabs/Airborne/Shadow.prefab.meta
  Assets/Scenes/SpringRemaster/SpringShadowForestScene.unity
  Assets/Scripts/Creature/Boss/EnemyAttackInfo.cs
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/Minion/ShadowOfHero/ShadowOfHero.cs
  Assets/Scripts/Creature/Minion/ShadowOfHero/SkillSwordAura.cs
  Assets/Scripts/Creature/Minion/ShadowOfHero/SkillSwordAura.cs.meta
  Assets/Scripts/Creature/Minion/ShadowOfHero/SwordAura.cs
  Assets/Scripts/Creature/Minion/ShadowOfHero/SwordAura.cs.meta
  Assets/Scripts/Creature/Player/Component/Collider/HtiCollider.cs
  Assets/Scripts/System/Game/AirborneController.cs
  Assets/Scripts/System/Game/AirborneController.cs.meta
Labels: feature, content(part), boss(part)

#293 Refact/280
  Assets/Prefabs/Boss/BossUi/Indicator.meta
  Assets/Prefabs/Boss/BossUi/Indicator/Circle.prefab
  Assets/Prefabs/Boss/BossUi/Indicator/Circle.prefab.meta
  Assets/Prefabs/Boss/BossUi/Indicator/CircleIndicator.prefab
  Assets/Prefabs/Boss/BossUi/Indicator/CircleIndicator.prefab.meta
  Assets/Prefabs/Boss/BossUi/Indicator/Cone.prefab
  Assets/Prefabs/Boss/BossUi/Indicator/Cone.prefab.meta
  Assets/Prefabs/Boss/BossUi/Indicator/ConeIndicator.prefab
  Assets/Prefabs/Boss/BossUi/Indicator/ConeIndicator.prefab.meta
  Assets/Prefabs/Boss/BossUi/Indicator/Line.prefab
  Assets/Prefabs/Boss/BossUi/Indicator/Line.prefab.meta
  Assets/Prefabs/Boss/BossUi/Indicator/LineIndicator.prefab
  Assets/Prefabs/Boss/BossUi/Indicator/LineIndicator.prefab.meta
  Assets/Prefabs/Boss/BossUi/Indicator/SkillIndicator.prefab
  Assets/Prefabs/Boss/BossUi/Indicator/SkillIndicator.prefab.meta
  Assets/Prefabs/Boss/MidBoss/MidBoss.prefab
  Assets/Scenes/DemoDay_Version_0207/SpringElf.unity
  Assets/Scripts/Creature/Boss/Boss.cs
  Assets/Scripts/Creature/Boss/Component/SkillIndicator.meta
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/CircleIndicator.cs
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/CircleIndicator.cs.meta
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/ConeIndicator.cs
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/ConeIndicator.cs.meta
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/IndicatorBase.cs
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/IndicatorBase.cs.meta
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/LineIndicator.cs
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/LineIndicator.cs.meta
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/SkllIndicatorDrawer.cs
  Assets/Scripts/Creature/Boss/Component/SkillIndicator/SkllIndicatorDrawer.cs.meta
  Assets/Scripts/Creature/Boss/Spring/Elf/Arrow.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Elf.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Seed.cs
  Assets/Scripts/Creature/Boss/Spring/Golem/Cube.cs
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/Minion/ShadowOfHero/ShadowOfHero.cs
  Assets/Scripts/Creature/Player/Component/Collider/HitCollider.cs
Labels: boss(part)

#296 Feat/285
  Assets/Scenes/EventTest/CameraTest.unity
  Assets/Scenes/EventTest/CameraTest.unity.meta
  Assets/Scripts/System/Event/Event/CinematicEvent/CameraEvents.cs
  Assets/Scripts/Visual/Camera.meta
  Assets/Scripts/Visual/Camera/CameraManager.cs
  Assets/Scripts/Visual/Camera/CameraManager.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
Labels: feature

#302 feat(ShadowOfHero.cs) : huckhuck 추가
  Assets/Scripts/Creature/Minion/ShadowOfHero/ShadowOfHero.cs
Labels: feature, content(part)

#295 Cinematic event/284
  Assets/Scenes/ReGraphic/Cinematic.unity
  Assets/Scenes/ReGraphic/Cinematic.unity.meta
  Assets/Scripts/System/Event/Controller/ChatController.cs
  Assets/Scripts/System/Event/Controller/EffectManager.cs
  Assets/Scripts/System/Event/Event/CinematicEvent/EffectEvents.cs
  Assets/Scripts/System/Event/Event/CinematicEvent/ImageEvents.cs
Labels: content(part)

#298 Refact/297
  Assets/Prefabs/Boss/MidBoss/MidBoss.prefab
  Assets/Prefabs/Boss/MidBoss/PratternInfo.meta
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MeleeAttack.asset
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MeleeAttack.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossArrow.asset
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossArrow.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossSeed.asset
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossSeed.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossSeedExplode.asset
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossSeedExplode.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossTrunk.asset
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossTrunk.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossVine.asset
  Assets/Prefabs/Boss/MidBoss/PratternInfo/MidBossVine.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternPrefab.meta
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MeleeAttack.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MeleeAttack.prefab.meta
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossArrow.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossArrow.prefab.meta
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossSeed.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossSeed.prefab.meta
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossSeedExplode.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossSeedExplode.prefab.meta
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossTrunk.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossTrunk.prefab.meta
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossVine.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossVine.prefab.meta
  Assets/Prefabs/Boss/MidBoss/PratternSound.meta
  Assets/Prefabs/Boss/MidBoss/PratternSound/MeleeAttackSounds.asset
  Assets/Prefabs/Boss/MidBoss/PratternSound/MeleeAttackSounds.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossArrowSounds.asset
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossArrowSounds.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossSeedExplodeSounds.asset
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossSeedExplodeSounds.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossSeedSounds.asset
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossSeedSounds.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossTrunkSounds.asset
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossTrunkSounds.asset.meta
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossVineSounds.asset
  Assets/Prefabs/Boss/MidBoss/PratternSound/MidBossVineSounds.asset.meta
  Assets/Scenes/DemoDay_Version_0207/SpringElf.unity
  Assets/Scripts/Creature/Boss/BossAttack.cs
  Assets/Scripts/Creature/Boss/BossAttack.cs.meta
  Assets/Scripts/Creature/Boss/Spring/Elf/Arrow.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Bomb.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Bomb.cs.meta
  Assets/Scripts/Creature/Boss/Spring/Elf/Elf.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/MeleeAttack.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/MeleeAttack.cs.meta
  Assets/Scripts/Creature/Boss/Spring/Elf/Seed.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Trunk.cs
  Assets/Scripts/Creature/Boss/Spring/Elf/Vine.cs
Labels: boss(part)

#281 refact(DivisionSlime.cs) : 분열 슬라임 코드 수정
  Assets/Prefabs/Minion/Slime/DivisionSlime.prefab
  Assets/Scenes/EventTest/DivisionSlimeTest.unity
  Assets/Scripts/Creature/Creature.cs
  Assets/Scripts/Creature/Minion/Component/detector/SimplePlayerDetector.cs
  Assets/Scripts/Creature/Minion/Component/detector/SimplePlayerDetector.cs.meta
  Assets/Scripts/Creature/Minion/Component/detector/SimplePlayerDistanceDetector.cs
  Assets/Scripts/Creature/Minion/Component/detector/SimplePlayerDistanceDetector.cs.meta
  Assets/Scripts/Creature/Minion/Slime/Components/SlimeAnimator.cs
  Assets/Scripts/Creature/Minion/Slime/DivisionSlime.cs
  Assets/Scripts/Creature/Minion/Slime/SlimeBase.cs
Labels: refactoring, content(part)

#273 Temple puzzle/257
  Assets/Art Resources/Cainos/Pixel Art Top Down - Basic/Tile Palette/TP Tree/New Palette.prefab
  Assets/Art Resources/Test.meta
  Assets/Art Resources/Test/Ball.gif
  Assets/Art Resources/Test/Ball.gif.meta
  Assets/Art Resources/Test/Goal.png
  Assets/Art Resources/Test/Goal.png.meta
  Assets/Art Resources/Test/Start.png
  Assets/Art Resources/Test/Start.png.meta
  Assets/Art Resources/Test/Straight.png
  Assets/Art Resources/Test/Straight.png.meta
  Assets/Art Resources/Test/TwoWay.png
  Assets/Art Resources/Test/TwoWay.png.meta
  Assets/Art Resources/Test/Wall.png
  Assets/Art Resources/Test/Wall.png.meta
  Assets/Prefabs/Puzzle/TemplePuzzle.meta
  Assets/Prefabs/Puzzle/TemplePuzzle/Ball.prefab
  Assets/Prefabs/Puzzle/TemplePuzzle/Ball.prefab.meta
  Assets/Prefabs/Puzzle/TemplePuzzle/Goal.prefab
  Assets/Prefabs/Puzzle/TemplePuzzle/Goal.prefab.meta
  Assets/Prefabs/Puzzle/TemplePuzzle/Start.prefab
  Assets/Prefabs/Puzzle/TemplePuzzle/Start.prefab.meta
  Assets/Prefabs/Puzzle/TemplePuzzle/Straight.prefab
  Assets/Prefabs/Puzzle/TemplePuzzle/Straight.prefab.meta
  Assets/Prefabs/Puzzle/TemplePuzzle/TwoWay.prefab
  Assets/Prefabs/Puzzle/TemplePuzzle/TwoWay.prefab.meta
  Assets/Prefabs/Puzzle/TemplePuzzle/Wall.prefab
  Assets/Prefabs/Puzzle/TemplePuzzle/Wall.prefab.meta
  Assets/Scenes/ReGraphic/TemplePuzzle.unity
  Assets/Scenes/ReGraphic/TemplePuzzle.unity.meta
  Assets/ScriptableObjects/Content.meta
  Assets/ScriptableObjects/Content/Curve.asset
  Assets/ScriptableObjects/Content/Curve.asset.meta
  Assets/ScriptableObjects/Content/Goal.asset
  Assets/ScriptableObjects/Content/Goal.asset.meta
  Assets/ScriptableObjects/Content/Start.asset
  Assets/ScriptableObjects/Content/Start.asset.meta
  Assets/ScriptableObjects/Content/Straight.asset
  Assets/ScriptableObjects/Content/Straight.asset.meta
  Assets/ScriptableObjects/Content/Wall.asset
  Assets/ScriptableObjects/Content/Wall.asset.meta
  Assets/Scripts/Map/Puzzle/TemplePuzzle.meta
  Assets/Scripts/Map/Puzzle/TemplePuzzle/BallButton.cs
  Assets/Scripts/Map/Puzzle/TemplePuzzle/BallButton.cs.meta
  Assets/Scripts/Map/Puzzle/TemplePuzzle/BallMovement.cs
  Assets/Scripts/Map/Puzzle/TemplePuzzle/BallMovement.cs.meta
  Assets/Scripts/Map/Puzzle/TemplePuzzle/ObjectGridLayout.cs
  Assets/Scripts/Map/Puzzle/TemplePuzzle/ObjectGridLayout.cs.meta
  Assets/Scripts/Map/Puzzle/TemplePuzzle/TemplePuzzleManager.cs
  Assets/Scripts/Map/Puzzle/TemplePuzzle/TemplePuzzleManager.cs.meta
  Assets/Scripts/Map/Puzzle/TemplePuzzle/TempleTile.cs
  Assets/Scripts/Map/Puzzle/TemplePuzzle/TempleTile.cs.meta
  Assets/Scripts/Map/Puzzle/TemplePuzzle/TempleTileData.cs
  Assets/Scripts/Map/Puzzle/TemplePuzzle/TempleTileData.cs.meta
  ProjectSettings/TagManager.asset
Labels: content(part), adventure(part)

#311 Fix/309
  Assets/Scripts/Creature/Player/Component/RuneComponent.cs
  Assets/Scripts/System/Game/Rune/Rune.cs
  Assets/Scripts/System/Game/Rune/RuneContext.cs
  Assets/Scripts/System/Game/Rune/RuneUI/RuneEquipListController.cs
Labels: rune(part)

#308 Golem Code refact
  Assets/Prefabs/Boss/Guardian/Guardian.prefab
  Assets/Prefabs/Boss/Guardian/PatternInfo.meta
  Assets/Prefabs/Boss/Guardian/PatternInfo/Cube.asset
  Assets/Prefabs/Boss/Guardian/PatternInfo/Cube.asset.meta
  Assets/Prefabs/Boss/Guardian/PatternInfo/Floor.asset
  Assets/Prefabs/Boss/Guardian/PatternInfo/Floor.asset.meta
  Assets/Prefabs/Boss/Guardian/PatternInfo/PushOutAttack.asset
  Assets/Prefabs/Boss/Guardian/PatternInfo/PushOutAttack.asset.meta
  Assets/Prefabs/Boss/Guardian/PatternInfo/ShockWave.asset
  Assets/Prefabs/Boss/Guardian/PatternInfo/ShockWave.asset.meta
  Assets/Prefabs/Boss/Guardian/PatternPrefab.meta
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Cube.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Cube.prefab.meta
  Assets/Prefabs/Boss/Guardian/PatternPrefab/CubeShadow.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/CubeShadow.prefab.meta
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Floor.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Floor.prefab.meta
  Assets/Prefabs/Boss/Guardian/PatternPrefab/PushOutAttack.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/PushOutAttack.prefab.meta
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Root.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Root.prefab.meta
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Shockwave.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Shockwave.prefab.meta
  Assets/Prefabs/Boss/Guardian/PatternSound.meta
  Assets/Prefabs/Boss/Guardian/PatternSound/CubeSounds.asset
  Assets/Prefabs/Boss/Guardian/PatternSound/CubeSounds.asset.meta
  Assets/Prefabs/Boss/Guardian/PatternSound/FloorSounds.asset
  Assets/Prefabs/Boss/Guardian/PatternSound/FloorSounds.asset.meta
  Assets/Prefabs/Boss/Guardian/PatternSound/PushOutAttackSounds.asset
  Assets/Prefabs/Boss/Guardian/PatternSound/PushOutAttackSounds.asset.meta
  Assets/Prefabs/Boss/Guardian/PatternSound/ShockWaveSounds.asset
  Assets/Prefabs/Boss/Guardian/PatternSound/ShockWaveSounds.asset.meta
  Assets/Scenes/DemoDay_Version_0207/SpringGolem.unity
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Boss.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Elf/Elf.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Elf/Seed.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Elf/Trunk.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/Cube.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/CubeShadow.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/Floor.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/Floor.cs.meta
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/Golem.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/GuardianAttack.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/GuardianAttack.cs.meta
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/Root.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/StateMachineMob.cs
  Assets/Scripts/Creature/Player/Controller/GrazeController.cs
Labels: boss(part)

#315 feat(PopUp UI Centerize)
  Assets/Prefabs/InGameManager.prefab
  Assets/Scripts/System/UI/PopupWindowController.cs
Labels: content(part)

#316 Implement ReSource
  Assets/Prefabs/Boss/Guardian/PatternPrefab/CubeShadow.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Floor.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/PushOutAttack.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/PushOutAttack.prefab.meta
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Root.prefab
  Assets/Prefabs/Boss/Guardian/PatternPrefab/Shockwave.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MeleeAttack.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossArrow.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossSeed.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossSeedExplode.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossTrunk.prefab
  Assets/Prefabs/Boss/MidBoss/PratternPrefab/MidBossVine.prefab
  Assets/Prefabs/Object/Shadowbottle.prefab
  Assets/Scenes/DemoDay_Version_0207/SpringElf.unity
  Assets/Scenes/DemoDay_Version_0207/SpringGolem.unity
  Assets/Scenes/SpringRemaster/TemplateScene.scenetemplate
  Assets/Scripts/Creature/Mob/Mob.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Elf/Elf.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/Cube.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/CubeShadow.cs
  Assets/Scripts/Creature/Mob/StateMachineMob/Boss/Spring/Golem/Golem.cs
Labels: art_resource, boss(part)

#318 Fix/317
  Assets/Prefabs/Boss/BossUi/Indicator/Circle.prefab
  Assets/Prefabs/Boss/BossUi/Indicator/Cone.prefab
  Assets/Prefabs/Boss/BossUi/Indicator/Line.prefab
  Assets/Scenes/Alpha Version/a0.0.1-1/SpringNorthForest.unity
  Assets/Scenes/YJ_map/Prefabs/middle_boss/MidBossMap.prefab
Labels: fix
